#! /usr/bin/env bash

for T in ww1 ww2
do
    rsync -avzH --exclude '*.bak' * ${T}:tmp/src/; ssh ${T} 'cd tmp/src; sudo make install;'
    /bin/rm -f /tmp/relport.html
    ssh ${T} 'sudo /opt/db2dps/bin/fnmcfg -b ' > /tmp/report.html

    if [ -s /tmp/report.html ]; then
        echo send report
    else
        echo no report
    fi
done

exit 0

